# Generated by Django 4.0.6 on 2022-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastpapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperhistory',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paperhistory',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='template_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
