# Generated by Django 4.0.6 on 2022-07-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Paper Code')),
                ('subject', models.CharField(choices=[('En', 'Tieng Anh')], max_length=2)),
                ('date', models.DateField(verbose_name='Paper Date')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_json', models.JSONField(verbose_name='Question JSON')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.paper')),
            ],
        ),
    ]
