# Generated by Django 4.0.6 on 2022-08-09 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='User starts at')),
                ('finish_time', models.TimeField(blank=True, null=True, verbose_name='User finishes at')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='questions.paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(auto_now=True, verbose_name='Submitted at')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='users',
        ),
        migrations.AlterField(
            model_name='choice',
            name='index',
            field=models.PositiveSmallIntegerField(verbose_name='Choice number'),
        ),
        migrations.AlterField(
            model_name='question',
            name='index',
            field=models.PositiveSmallIntegerField(verbose_name='Question number'),
        ),
        migrations.DeleteModel(
            name='UserQuestion',
        ),
        migrations.AddField(
            model_name='questionhistory',
            name='answer_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.choice'),
        ),
        migrations.AddField(
            model_name='questionhistory',
            name='paper_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.paperhistory'),
        ),
        migrations.AddField(
            model_name='questionhistory',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
