# Generated by Django 4.0.6 on 2022-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_json',
            new_name='json_data',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], max_length=1),
        ),
    ]
