# Generated by Django 4.0.6 on 2022-08-12 17:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(verbose_name='JSON Data')),
                ('correct_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D')], max_length=1), size=None)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('updated_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('n', '---'), ('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D')], max_length=1), size=None)),
                ('correct_option_count', models.SmallIntegerField(null=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('updated_time', models.TimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pastpapers.pastpaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
